#!/bin/bash

[ -z "$1" ] && echo "usage: ./build <directory>" && echo "e.g. ./build disass" && exit 1

if [ -f .env ]
then
  export $(cat .env | sed 's/#.*//g' | xargs)
fi

[ -z "$JAVA_PATH" ] && JAVA_PATH=java
[ -z "$JAVAC_PATH" ] && JAVAC_PATH=javac
[ -z "$APKTOOL_PATH" ] && APKTOOL_PATH=/opt/apktool.jar
[ -z "$UBER_APK_SIGNER_PATH" ] && UBER_APK_SIGNER_PATH=/opt/uber-apk-signer-1.2.1.jar
[ -z "$ANDROID_SDK_ROOT" ] && ANDROID_SDK_ROOT=~/Android/Sdk
[ -z "$BAKSMALI_PATH" ] && BAKSMALI_PATH=/opt/baksmali.jar
[ -z "$BUILD_COMPANION" ] && BUILD_COMPANION=/opt/build-companion

echo "JAVA_PATH: $JAVA_PATH"
echo "APKTOOL_PATH: $APKTOOL_PATH"
echo "UBER_APK_SIGNER_PATH: $UBER_APK_SIGNER_PATH"

cd $1

APK_PATH=./dist/twitch.apk

$JAVA_PATH -Xmx6g -jar $APKTOOL_PATH b . --use-aapt2 &&

if [ -z "$KS" ]; then

	$JAVA_PATH -jar $UBER_APK_SIGNER_PATH -a $APK_PATH
	rm $APK_PATH &&
	mv ./dist/twitch-aligned-debugSigned.apk $APK_PATH
else
	$JAVA_PATH -jar $UBER_APK_SIGNER_PATH -a $APK_PATH --ks $KS --ksAlias bttv-android --ksPass $KSPASS --ksKeyPass $KSPASS
	rm $APK_PATH &&
	mv ./dist/twitch-aligned-signed.apk $APK_PATH
fi

echo "Done: $APK_PATH"

